SELECT
    CHILD.ID
FROM ECOLI_DATA AS CHILD

-- 3세대 개체와 2세대 부모 연결
JOIN ECOLI_DATA AS PARENT
    ON CHILD.PARENT_ID = PARENT.ID

-- 2세대 부모와 1세대 조부모 연결
JOIN ECOLI_DATA AS GRANDPARENT
    ON PARENT.PARENT_ID = GRANDPARENT.ID

-- 부모가 없는 개체가 1세대
WHERE GRANDPARENT.PARENT_ID IS NULL

-- 3세대 개체의 ID를 오름차순 정렬
ORDER BY CHILD.ID;